/**
 * Chess Application GUI
 * @author Pete Stamos petestamos@gmail.com
 */
public class ChessGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChessGUI
     */
    public ChessGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        B8 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        E8 = new javax.swing.JButton();
        G8 = new javax.swing.JButton();
        H8 = new javax.swing.JButton();
        H7 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        G7 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        H6 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        H1 = new javax.swing.JButton();
        label8 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        labelB = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();
        labelD = new javax.swing.JLabel();
        labelE = new javax.swing.JLabel();
        labelF = new javax.swing.JLabel();
        labelG = new javax.swing.JLabel();
        labelH = new javax.swing.JLabel();
        outOfPlayPanel = new javax.swing.JPanel();
        blackLabel = new javax.swing.JLabel();
        whiteLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        durationPanel = new javax.swing.JPanel();
        durationText = new javax.swing.JLabel();
        menuBarPanel = new javax.swing.JPanel();
        newGameButton = new javax.swing.JButton();
        saveGameButton = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LaboonChess");
        setMaximumSize(new java.awt.Dimension(700, 515));
        setMinimumSize(new java.awt.Dimension(700, 515));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPanel.setMaximumSize(new java.awt.Dimension(402, 402));
        mainPanel.setMinimumSize(new java.awt.Dimension(402, 402));
        mainPanel.setPreferredSize(new java.awt.Dimension(402, 402));
        mainPanel.setSize(new java.awt.Dimension(402, 402));

        B8.setBackground(new java.awt.Color(153, 153, 153));
        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-knight.png"))); // NOI18N
        B8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B8.setContentAreaFilled(false);
        B8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B8.setMaximumSize(new java.awt.Dimension(50, 50));
        B8.setMinimumSize(new java.awt.Dimension(50, 50));
        B8.setOpaque(true);
        B8.setPreferredSize(new java.awt.Dimension(50, 50));
        B8.setSize(new java.awt.Dimension(50, 50));

        A8.setBackground(new java.awt.Color(255, 255, 255));
        A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-rook.png"))); // NOI18N
        A8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A8.setContentAreaFilled(false);
        A8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A8.setMaximumSize(new java.awt.Dimension(50, 50));
        A8.setMinimumSize(new java.awt.Dimension(50, 50));
        A8.setOpaque(true);
        A8.setPreferredSize(new java.awt.Dimension(50, 50));
        A8.setSize(new java.awt.Dimension(50, 50));

        D8.setBackground(new java.awt.Color(153, 153, 153));
        D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-king.png"))); // NOI18N
        D8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D8.setContentAreaFilled(false);
        D8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D8.setMaximumSize(new java.awt.Dimension(50, 50));
        D8.setMinimumSize(new java.awt.Dimension(50, 50));
        D8.setOpaque(true);
        D8.setPreferredSize(new java.awt.Dimension(50, 50));
        D8.setSize(new java.awt.Dimension(50, 50));

        C8.setBackground(new java.awt.Color(255, 255, 255));
        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-bishop.png"))); // NOI18N
        C8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C8.setContentAreaFilled(false);
        C8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C8.setMaximumSize(new java.awt.Dimension(50, 50));
        C8.setMinimumSize(new java.awt.Dimension(50, 50));
        C8.setOpaque(true);
        C8.setPreferredSize(new java.awt.Dimension(50, 50));
        C8.setSize(new java.awt.Dimension(50, 50));

        F8.setBackground(new java.awt.Color(153, 153, 153));
        F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-bishop.png"))); // NOI18N
        F8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F8.setContentAreaFilled(false);
        F8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F8.setMaximumSize(new java.awt.Dimension(50, 50));
        F8.setMinimumSize(new java.awt.Dimension(50, 50));
        F8.setOpaque(true);
        F8.setPreferredSize(new java.awt.Dimension(50, 50));
        F8.setSize(new java.awt.Dimension(50, 50));

        E8.setBackground(new java.awt.Color(255, 255, 255));
        E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-queen.png"))); // NOI18N
        E8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E8.setContentAreaFilled(false);
        E8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E8.setMaximumSize(new java.awt.Dimension(50, 50));
        E8.setMinimumSize(new java.awt.Dimension(50, 50));
        E8.setOpaque(true);
        E8.setPreferredSize(new java.awt.Dimension(50, 50));
        E8.setSize(new java.awt.Dimension(50, 50));

        G8.setBackground(new java.awt.Color(255, 255, 255));
        G8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-knight.png"))); // NOI18N
        G8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G8.setContentAreaFilled(false);
        G8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G8.setMaximumSize(new java.awt.Dimension(50, 50));
        G8.setMinimumSize(new java.awt.Dimension(50, 50));
        G8.setOpaque(true);
        G8.setPreferredSize(new java.awt.Dimension(50, 50));
        G8.setSize(new java.awt.Dimension(50, 50));

        H8.setBackground(new java.awt.Color(153, 153, 153));
        H8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-rook.png"))); // NOI18N
        H8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H8.setContentAreaFilled(false);
        H8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H8.setMaximumSize(new java.awt.Dimension(50, 50));
        H8.setMinimumSize(new java.awt.Dimension(50, 50));
        H8.setOpaque(true);
        H8.setPreferredSize(new java.awt.Dimension(50, 50));
        H8.setSize(new java.awt.Dimension(50, 50));

        H7.setBackground(new java.awt.Color(255, 255, 255));
        H7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        H7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H7.setContentAreaFilled(false);
        H7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H7.setMaximumSize(new java.awt.Dimension(50, 50));
        H7.setMinimumSize(new java.awt.Dimension(50, 50));
        H7.setOpaque(true);
        H7.setPreferredSize(new java.awt.Dimension(50, 50));
        H7.setSize(new java.awt.Dimension(50, 50));

        B7.setBackground(new java.awt.Color(255, 255, 255));
        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        B7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B7.setContentAreaFilled(false);
        B7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B7.setMaximumSize(new java.awt.Dimension(50, 50));
        B7.setMinimumSize(new java.awt.Dimension(50, 50));
        B7.setOpaque(true);
        B7.setPreferredSize(new java.awt.Dimension(50, 50));
        B7.setSize(new java.awt.Dimension(50, 50));

        A7.setBackground(new java.awt.Color(153, 153, 153));
        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        A7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A7.setContentAreaFilled(false);
        A7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A7.setMaximumSize(new java.awt.Dimension(50, 50));
        A7.setMinimumSize(new java.awt.Dimension(50, 50));
        A7.setOpaque(true);
        A7.setPreferredSize(new java.awt.Dimension(50, 50));
        A7.setSize(new java.awt.Dimension(50, 50));

        D7.setBackground(new java.awt.Color(255, 255, 255));
        D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        D7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D7.setContentAreaFilled(false);
        D7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D7.setMaximumSize(new java.awt.Dimension(50, 50));
        D7.setMinimumSize(new java.awt.Dimension(50, 50));
        D7.setOpaque(true);
        D7.setPreferredSize(new java.awt.Dimension(50, 50));
        D7.setSize(new java.awt.Dimension(50, 50));

        C7.setBackground(new java.awt.Color(153, 153, 153));
        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        C7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C7.setContentAreaFilled(false);
        C7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C7.setMaximumSize(new java.awt.Dimension(50, 50));
        C7.setMinimumSize(new java.awt.Dimension(50, 50));
        C7.setOpaque(true);
        C7.setPreferredSize(new java.awt.Dimension(50, 50));
        C7.setSize(new java.awt.Dimension(50, 50));

        F7.setBackground(new java.awt.Color(255, 255, 255));
        F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        F7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F7.setContentAreaFilled(false);
        F7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F7.setMaximumSize(new java.awt.Dimension(50, 50));
        F7.setMinimumSize(new java.awt.Dimension(50, 50));
        F7.setOpaque(true);
        F7.setPreferredSize(new java.awt.Dimension(50, 50));
        F7.setSize(new java.awt.Dimension(50, 50));

        E7.setBackground(new java.awt.Color(153, 153, 153));
        E7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        E7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E7.setContentAreaFilled(false);
        E7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E7.setMaximumSize(new java.awt.Dimension(50, 50));
        E7.setMinimumSize(new java.awt.Dimension(50, 50));
        E7.setOpaque(true);
        E7.setPreferredSize(new java.awt.Dimension(50, 50));
        E7.setSize(new java.awt.Dimension(50, 50));

        G7.setBackground(new java.awt.Color(153, 153, 153));
        G7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-pawn.png"))); // NOI18N
        G7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G7.setContentAreaFilled(false);
        G7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G7.setMaximumSize(new java.awt.Dimension(50, 50));
        G7.setMinimumSize(new java.awt.Dimension(50, 50));
        G7.setOpaque(true);
        G7.setPreferredSize(new java.awt.Dimension(50, 50));
        G7.setSize(new java.awt.Dimension(50, 50));

        F6.setBackground(new java.awt.Color(153, 153, 153));
        F6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F6.setContentAreaFilled(false);
        F6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F6.setMaximumSize(new java.awt.Dimension(50, 50));
        F6.setMinimumSize(new java.awt.Dimension(50, 50));
        F6.setOpaque(true);
        F6.setPreferredSize(new java.awt.Dimension(50, 50));
        F6.setSize(new java.awt.Dimension(50, 50));

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B5.setContentAreaFilled(false);
        B5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B5.setMaximumSize(new java.awt.Dimension(50, 50));
        B5.setMinimumSize(new java.awt.Dimension(50, 50));
        B5.setOpaque(true);
        B5.setPreferredSize(new java.awt.Dimension(50, 50));
        B5.setSize(new java.awt.Dimension(50, 50));

        E6.setBackground(new java.awt.Color(255, 255, 255));
        E6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E6.setContentAreaFilled(false);
        E6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E6.setMaximumSize(new java.awt.Dimension(50, 50));
        E6.setMinimumSize(new java.awt.Dimension(50, 50));
        E6.setOpaque(true);
        E6.setPreferredSize(new java.awt.Dimension(50, 50));
        E6.setSize(new java.awt.Dimension(50, 50));

        A5.setBackground(new java.awt.Color(153, 153, 153));
        A5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A5.setContentAreaFilled(false);
        A5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A5.setMaximumSize(new java.awt.Dimension(50, 50));
        A5.setMinimumSize(new java.awt.Dimension(50, 50));
        A5.setOpaque(true);
        A5.setPreferredSize(new java.awt.Dimension(50, 50));
        A5.setSize(new java.awt.Dimension(50, 50));

        G6.setBackground(new java.awt.Color(255, 255, 255));
        G6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G6.setContentAreaFilled(false);
        G6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G6.setMaximumSize(new java.awt.Dimension(50, 50));
        G6.setMinimumSize(new java.awt.Dimension(50, 50));
        G6.setOpaque(true);
        G6.setPreferredSize(new java.awt.Dimension(50, 50));
        G6.setSize(new java.awt.Dimension(50, 50));

        D5.setBackground(new java.awt.Color(255, 255, 255));
        D5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D5.setContentAreaFilled(false);
        D5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D5.setMaximumSize(new java.awt.Dimension(50, 50));
        D5.setMinimumSize(new java.awt.Dimension(50, 50));
        D5.setOpaque(true);
        D5.setPreferredSize(new java.awt.Dimension(50, 50));
        D5.setSize(new java.awt.Dimension(50, 50));

        C5.setBackground(new java.awt.Color(153, 153, 153));
        C5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C5.setContentAreaFilled(false);
        C5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C5.setMaximumSize(new java.awt.Dimension(50, 50));
        C5.setMinimumSize(new java.awt.Dimension(50, 50));
        C5.setOpaque(true);
        C5.setPreferredSize(new java.awt.Dimension(50, 50));
        C5.setSize(new java.awt.Dimension(50, 50));

        F5.setBackground(new java.awt.Color(255, 255, 255));
        F5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F5.setContentAreaFilled(false);
        F5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F5.setMaximumSize(new java.awt.Dimension(50, 50));
        F5.setMinimumSize(new java.awt.Dimension(50, 50));
        F5.setOpaque(true);
        F5.setPreferredSize(new java.awt.Dimension(50, 50));
        F5.setSize(new java.awt.Dimension(50, 50));

        E5.setBackground(new java.awt.Color(153, 153, 153));
        E5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E5.setContentAreaFilled(false);
        E5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E5.setMaximumSize(new java.awt.Dimension(50, 50));
        E5.setMinimumSize(new java.awt.Dimension(50, 50));
        E5.setOpaque(true);
        E5.setPreferredSize(new java.awt.Dimension(50, 50));
        E5.setSize(new java.awt.Dimension(50, 50));

        G5.setBackground(new java.awt.Color(153, 153, 153));
        G5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G5.setContentAreaFilled(false);
        G5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G5.setMaximumSize(new java.awt.Dimension(50, 50));
        G5.setMinimumSize(new java.awt.Dimension(50, 50));
        G5.setOpaque(true);
        G5.setPreferredSize(new java.awt.Dimension(50, 50));
        G5.setSize(new java.awt.Dimension(50, 50));

        B6.setBackground(new java.awt.Color(153, 153, 153));
        B6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B6.setContentAreaFilled(false);
        B6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B6.setMaximumSize(new java.awt.Dimension(50, 50));
        B6.setMinimumSize(new java.awt.Dimension(50, 50));
        B6.setOpaque(true);
        B6.setPreferredSize(new java.awt.Dimension(50, 50));
        B6.setSize(new java.awt.Dimension(50, 50));

        A6.setBackground(new java.awt.Color(255, 255, 255));
        A6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A6.setContentAreaFilled(false);
        A6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A6.setMaximumSize(new java.awt.Dimension(50, 50));
        A6.setMinimumSize(new java.awt.Dimension(50, 50));
        A6.setOpaque(true);
        A6.setPreferredSize(new java.awt.Dimension(50, 50));
        A6.setSize(new java.awt.Dimension(50, 50));

        H6.setBackground(new java.awt.Color(153, 153, 153));
        H6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H6.setContentAreaFilled(false);
        H6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H6.setMaximumSize(new java.awt.Dimension(50, 50));
        H6.setMinimumSize(new java.awt.Dimension(50, 50));
        H6.setOpaque(true);
        H6.setPreferredSize(new java.awt.Dimension(50, 50));
        H6.setSize(new java.awt.Dimension(50, 50));

        D6.setBackground(new java.awt.Color(153, 153, 153));
        D6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D6.setContentAreaFilled(false);
        D6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D6.setMaximumSize(new java.awt.Dimension(50, 50));
        D6.setMinimumSize(new java.awt.Dimension(50, 50));
        D6.setOpaque(true);
        D6.setPreferredSize(new java.awt.Dimension(50, 50));
        D6.setSize(new java.awt.Dimension(50, 50));

        H5.setBackground(new java.awt.Color(255, 255, 255));
        H5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H5.setContentAreaFilled(false);
        H5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H5.setMaximumSize(new java.awt.Dimension(50, 50));
        H5.setMinimumSize(new java.awt.Dimension(50, 50));
        H5.setOpaque(true);
        H5.setPreferredSize(new java.awt.Dimension(50, 50));
        H5.setSize(new java.awt.Dimension(50, 50));

        C6.setBackground(new java.awt.Color(255, 255, 255));
        C6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C6.setContentAreaFilled(false);
        C6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C6.setMaximumSize(new java.awt.Dimension(50, 50));
        C6.setMinimumSize(new java.awt.Dimension(50, 50));
        C6.setOpaque(true);
        C6.setPreferredSize(new java.awt.Dimension(50, 50));
        C6.setSize(new java.awt.Dimension(50, 50));

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-knight.png"))); // NOI18N
        B1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B1.setContentAreaFilled(false);
        B1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B1.setMaximumSize(new java.awt.Dimension(50, 50));
        B1.setMinimumSize(new java.awt.Dimension(50, 50));
        B1.setOpaque(true);
        B1.setPreferredSize(new java.awt.Dimension(50, 50));
        B1.setSize(new java.awt.Dimension(50, 50));

        A1.setBackground(new java.awt.Color(153, 153, 153));
        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-rook.png"))); // NOI18N
        A1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A1.setContentAreaFilled(false);
        A1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A1.setMaximumSize(new java.awt.Dimension(50, 50));
        A1.setMinimumSize(new java.awt.Dimension(50, 50));
        A1.setOpaque(true);
        A1.setPreferredSize(new java.awt.Dimension(50, 50));
        A1.setSize(new java.awt.Dimension(50, 50));

        D1.setBackground(new java.awt.Color(255, 255, 255));
        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-king.png"))); // NOI18N
        D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D1.setContentAreaFilled(false);
        D1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D1.setMaximumSize(new java.awt.Dimension(50, 50));
        D1.setMinimumSize(new java.awt.Dimension(50, 50));
        D1.setOpaque(true);
        D1.setPreferredSize(new java.awt.Dimension(50, 50));
        D1.setSize(new java.awt.Dimension(50, 50));

        C1.setBackground(new java.awt.Color(153, 153, 153));
        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-bishop.png"))); // NOI18N
        C1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C1.setContentAreaFilled(false);
        C1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C1.setMaximumSize(new java.awt.Dimension(50, 50));
        C1.setMinimumSize(new java.awt.Dimension(50, 50));
        C1.setOpaque(true);
        C1.setPreferredSize(new java.awt.Dimension(50, 50));
        C1.setSize(new java.awt.Dimension(50, 50));

        F1.setBackground(new java.awt.Color(255, 255, 255));
        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-bishop.png"))); // NOI18N
        F1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F1.setContentAreaFilled(false);
        F1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F1.setMaximumSize(new java.awt.Dimension(50, 50));
        F1.setMinimumSize(new java.awt.Dimension(50, 50));
        F1.setOpaque(true);
        F1.setPreferredSize(new java.awt.Dimension(50, 50));
        F1.setSize(new java.awt.Dimension(50, 50));

        E1.setBackground(new java.awt.Color(153, 153, 153));
        E1.setForeground(new java.awt.Color(255, 255, 255));
        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-queen.png"))); // NOI18N
        E1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E1.setContentAreaFilled(false);
        E1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E1.setMaximumSize(new java.awt.Dimension(50, 50));
        E1.setMinimumSize(new java.awt.Dimension(50, 50));
        E1.setOpaque(true);
        E1.setPreferredSize(new java.awt.Dimension(50, 50));
        E1.setSize(new java.awt.Dimension(50, 50));

        G1.setBackground(new java.awt.Color(153, 153, 153));
        G1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-knight.png"))); // NOI18N
        G1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G1.setContentAreaFilled(false);
        G1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G1.setMaximumSize(new java.awt.Dimension(50, 50));
        G1.setMinimumSize(new java.awt.Dimension(50, 50));
        G1.setOpaque(true);
        G1.setPreferredSize(new java.awt.Dimension(50, 50));
        G1.setSize(new java.awt.Dimension(50, 50));

        B2.setBackground(new java.awt.Color(153, 153, 153));
        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        B2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B2.setContentAreaFilled(false);
        B2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B2.setMaximumSize(new java.awt.Dimension(50, 50));
        B2.setMinimumSize(new java.awt.Dimension(50, 50));
        B2.setOpaque(true);
        B2.setPreferredSize(new java.awt.Dimension(50, 50));
        B2.setSize(new java.awt.Dimension(50, 50));

        A2.setBackground(new java.awt.Color(255, 255, 255));
        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        A2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A2.setContentAreaFilled(false);
        A2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A2.setMaximumSize(new java.awt.Dimension(50, 50));
        A2.setMinimumSize(new java.awt.Dimension(50, 50));
        A2.setOpaque(true);
        A2.setPreferredSize(new java.awt.Dimension(50, 50));
        A2.setSize(new java.awt.Dimension(50, 50));

        D2.setBackground(new java.awt.Color(153, 153, 153));
        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        D2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D2.setContentAreaFilled(false);
        D2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D2.setMaximumSize(new java.awt.Dimension(50, 50));
        D2.setMinimumSize(new java.awt.Dimension(50, 50));
        D2.setOpaque(true);
        D2.setPreferredSize(new java.awt.Dimension(50, 50));
        D2.setSize(new java.awt.Dimension(50, 50));

        G4.setBackground(new java.awt.Color(255, 255, 255));
        G4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G4.setContentAreaFilled(false);
        G4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G4.setMaximumSize(new java.awt.Dimension(50, 50));
        G4.setMinimumSize(new java.awt.Dimension(50, 50));
        G4.setOpaque(true);
        G4.setPreferredSize(new java.awt.Dimension(50, 50));
        G4.setSize(new java.awt.Dimension(50, 50));

        C2.setBackground(new java.awt.Color(255, 255, 255));
        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        C2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C2.setContentAreaFilled(false);
        C2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C2.setMaximumSize(new java.awt.Dimension(50, 50));
        C2.setMinimumSize(new java.awt.Dimension(50, 50));
        C2.setOpaque(true);
        C2.setPreferredSize(new java.awt.Dimension(50, 50));
        C2.setSize(new java.awt.Dimension(50, 50));

        H4.setBackground(new java.awt.Color(153, 153, 153));
        H4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H4.setContentAreaFilled(false);
        H4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H4.setMaximumSize(new java.awt.Dimension(50, 50));
        H4.setMinimumSize(new java.awt.Dimension(50, 50));
        H4.setOpaque(true);
        H4.setPreferredSize(new java.awt.Dimension(50, 50));
        H4.setSize(new java.awt.Dimension(50, 50));

        F2.setBackground(new java.awt.Color(153, 153, 153));
        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        F2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F2.setContentAreaFilled(false);
        F2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F2.setMaximumSize(new java.awt.Dimension(50, 50));
        F2.setMinimumSize(new java.awt.Dimension(50, 50));
        F2.setOpaque(true);
        F2.setPreferredSize(new java.awt.Dimension(50, 50));
        F2.setSize(new java.awt.Dimension(50, 50));

        H3.setBackground(new java.awt.Color(255, 255, 255));
        H3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H3.setContentAreaFilled(false);
        H3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H3.setMaximumSize(new java.awt.Dimension(50, 50));
        H3.setMinimumSize(new java.awt.Dimension(50, 50));
        H3.setOpaque(true);
        H3.setPreferredSize(new java.awt.Dimension(50, 50));
        H3.setSize(new java.awt.Dimension(50, 50));

        E2.setBackground(new java.awt.Color(255, 255, 255));
        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        E2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E2.setContentAreaFilled(false);
        E2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E2.setMaximumSize(new java.awt.Dimension(50, 50));
        E2.setMinimumSize(new java.awt.Dimension(50, 50));
        E2.setOpaque(true);
        E2.setPreferredSize(new java.awt.Dimension(50, 50));
        E2.setSize(new java.awt.Dimension(50, 50));

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B3.setContentAreaFilled(false);
        B3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B3.setMaximumSize(new java.awt.Dimension(50, 50));
        B3.setMinimumSize(new java.awt.Dimension(50, 50));
        B3.setOpaque(true);
        B3.setPreferredSize(new java.awt.Dimension(50, 50));
        B3.setSize(new java.awt.Dimension(50, 50));

        G2.setBackground(new java.awt.Color(255, 255, 255));
        G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        G2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G2.setContentAreaFilled(false);
        G2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G2.setMaximumSize(new java.awt.Dimension(50, 50));
        G2.setMinimumSize(new java.awt.Dimension(50, 50));
        G2.setOpaque(true);
        G2.setPreferredSize(new java.awt.Dimension(50, 50));
        G2.setSize(new java.awt.Dimension(50, 50));

        A3.setBackground(new java.awt.Color(153, 153, 153));
        A3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A3.setContentAreaFilled(false);
        A3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A3.setMaximumSize(new java.awt.Dimension(50, 50));
        A3.setMinimumSize(new java.awt.Dimension(50, 50));
        A3.setOpaque(true);
        A3.setPreferredSize(new java.awt.Dimension(50, 50));
        A3.setSize(new java.awt.Dimension(50, 50));

        D3.setBackground(new java.awt.Color(255, 255, 255));
        D3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D3.setContentAreaFilled(false);
        D3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D3.setMaximumSize(new java.awt.Dimension(50, 50));
        D3.setMinimumSize(new java.awt.Dimension(50, 50));
        D3.setOpaque(true);
        D3.setPreferredSize(new java.awt.Dimension(50, 50));
        D3.setSize(new java.awt.Dimension(50, 50));

        C3.setBackground(new java.awt.Color(153, 153, 153));
        C3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C3.setContentAreaFilled(false);
        C3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C3.setMaximumSize(new java.awt.Dimension(50, 50));
        C3.setMinimumSize(new java.awt.Dimension(50, 50));
        C3.setOpaque(true);
        C3.setPreferredSize(new java.awt.Dimension(50, 50));
        C3.setSize(new java.awt.Dimension(50, 50));

        F3.setBackground(new java.awt.Color(255, 255, 255));
        F3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F3.setContentAreaFilled(false);
        F3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F3.setMaximumSize(new java.awt.Dimension(50, 50));
        F3.setMinimumSize(new java.awt.Dimension(50, 50));
        F3.setOpaque(true);
        F3.setPreferredSize(new java.awt.Dimension(50, 50));
        F3.setSize(new java.awt.Dimension(50, 50));

        E3.setBackground(new java.awt.Color(153, 153, 153));
        E3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E3.setContentAreaFilled(false);
        E3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E3.setMaximumSize(new java.awt.Dimension(50, 50));
        E3.setMinimumSize(new java.awt.Dimension(50, 50));
        E3.setOpaque(true);
        E3.setPreferredSize(new java.awt.Dimension(50, 50));
        E3.setSize(new java.awt.Dimension(50, 50));

        G3.setBackground(new java.awt.Color(153, 153, 153));
        G3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        G3.setContentAreaFilled(false);
        G3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        G3.setMaximumSize(new java.awt.Dimension(50, 50));
        G3.setMinimumSize(new java.awt.Dimension(50, 50));
        G3.setOpaque(true);
        G3.setPreferredSize(new java.awt.Dimension(50, 50));
        G3.setSize(new java.awt.Dimension(50, 50));

        B4.setBackground(new java.awt.Color(153, 153, 153));
        B4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B4.setContentAreaFilled(false);
        B4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        B4.setMaximumSize(new java.awt.Dimension(50, 50));
        B4.setMinimumSize(new java.awt.Dimension(50, 50));
        B4.setOpaque(true);
        B4.setPreferredSize(new java.awt.Dimension(50, 50));
        B4.setSize(new java.awt.Dimension(50, 50));

        A4.setBackground(new java.awt.Color(255, 255, 255));
        A4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        A4.setContentAreaFilled(false);
        A4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        A4.setMaximumSize(new java.awt.Dimension(50, 50));
        A4.setMinimumSize(new java.awt.Dimension(50, 50));
        A4.setOpaque(true);
        A4.setPreferredSize(new java.awt.Dimension(50, 50));
        A4.setSize(new java.awt.Dimension(50, 50));

        D4.setBackground(new java.awt.Color(153, 153, 153));
        D4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        D4.setContentAreaFilled(false);
        D4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        D4.setMaximumSize(new java.awt.Dimension(50, 50));
        D4.setMinimumSize(new java.awt.Dimension(50, 50));
        D4.setOpaque(true);
        D4.setPreferredSize(new java.awt.Dimension(50, 50));
        D4.setSize(new java.awt.Dimension(50, 50));

        C4.setBackground(new java.awt.Color(255, 255, 255));
        C4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C4.setContentAreaFilled(false);
        C4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        C4.setMaximumSize(new java.awt.Dimension(50, 50));
        C4.setMinimumSize(new java.awt.Dimension(50, 50));
        C4.setOpaque(true);
        C4.setPreferredSize(new java.awt.Dimension(50, 50));
        C4.setSize(new java.awt.Dimension(50, 50));

        F4.setBackground(new java.awt.Color(153, 153, 153));
        F4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        F4.setContentAreaFilled(false);
        F4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        F4.setMaximumSize(new java.awt.Dimension(50, 50));
        F4.setMinimumSize(new java.awt.Dimension(50, 50));
        F4.setOpaque(true);
        F4.setPreferredSize(new java.awt.Dimension(50, 50));
        F4.setSize(new java.awt.Dimension(50, 50));

        E4.setBackground(new java.awt.Color(255, 255, 255));
        E4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        E4.setContentAreaFilled(false);
        E4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        E4.setMaximumSize(new java.awt.Dimension(50, 50));
        E4.setMinimumSize(new java.awt.Dimension(50, 50));
        E4.setOpaque(true);
        E4.setPreferredSize(new java.awt.Dimension(50, 50));
        E4.setSize(new java.awt.Dimension(50, 50));

        H2.setBackground(new java.awt.Color(153, 153, 153));
        H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-pawn.png"))); // NOI18N
        H2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H2.setContentAreaFilled(false);
        H2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H2.setMaximumSize(new java.awt.Dimension(50, 50));
        H2.setMinimumSize(new java.awt.Dimension(50, 50));
        H2.setOpaque(true);
        H2.setPreferredSize(new java.awt.Dimension(50, 50));
        H2.setSize(new java.awt.Dimension(50, 50));

        H1.setBackground(new java.awt.Color(255, 255, 255));
        H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-rook.png"))); // NOI18N
        H1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        H1.setContentAreaFilled(false);
        H1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        H1.setMaximumSize(new java.awt.Dimension(50, 50));
        H1.setMinimumSize(new java.awt.Dimension(50, 50));
        H1.setOpaque(true);
        H1.setPreferredSize(new java.awt.Dimension(50, 50));
        H1.setSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        label8.setText("8");

        label7.setText("7");

        label6.setText("6");

        label5.setText("5");

        label4.setText("4");

        label3.setText("3");

        label2.setText("2");

        label1.setText("1");

        labelA.setText("A");

        labelB.setText("B");

        labelC.setText("C");

        labelD.setText("D");

        labelE.setText("E");

        labelF.setText("F");

        labelG.setText("G");

        labelH.setText("H");

        outOfPlayPanel.setBackground(new java.awt.Color(204, 204, 204));
        outOfPlayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        blackLabel.setText("Black");

        whiteLabel.setText("White");

        javax.swing.GroupLayout outOfPlayPanelLayout = new javax.swing.GroupLayout(outOfPlayPanel);
        outOfPlayPanel.setLayout(outOfPlayPanelLayout);
        outOfPlayPanelLayout.setHorizontalGroup(
            outOfPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(outOfPlayPanelLayout.createSequentialGroup()
                .addGroup(outOfPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outOfPlayPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(whiteLabel))
                    .addGroup(outOfPlayPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(blackLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outOfPlayPanelLayout.setVerticalGroup(
            outOfPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outOfPlayPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(blackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(whiteLabel)
                .addGap(12, 12, 12))
        );

        durationPanel.setBackground(new java.awt.Color(204, 204, 204));
        durationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        durationText.setText("Duration: 00:00");

        javax.swing.GroupLayout durationPanelLayout = new javax.swing.GroupLayout(durationPanel);
        durationPanel.setLayout(durationPanelLayout);
        durationPanelLayout.setHorizontalGroup(
            durationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durationPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(durationText)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        durationPanelLayout.setVerticalGroup(
            durationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(durationText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBarPanel.setBackground(new java.awt.Color(204, 204, 204));
        menuBarPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        newGameButton.setText("New Game");
        newGameButton.setBorderPainted(false);
        newGameButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        newGameButton.setRequestFocusEnabled(false);

        saveGameButton.setText("Save Game");
        saveGameButton.setBorderPainted(false);
        saveGameButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        saveGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameButtonActionPerformed(evt);
            }
        });

        loadGameButton.setText("Load Game");
        loadGameButton.setBorderPainted(false);
        loadGameButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        loadGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarPanelLayout = new javax.swing.GroupLayout(menuBarPanel);
        menuBarPanel.setLayout(menuBarPanelLayout);
        menuBarPanelLayout.setHorizontalGroup(
            menuBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarPanelLayout.createSequentialGroup()
                .addComponent(newGameButton)
                .addGap(0, 0, 0)
                .addComponent(saveGameButton)
                .addGap(0, 0, 0)
                .addComponent(loadGameButton)
                .addGap(0, 0, 0))
        );
        menuBarPanelLayout.setVerticalGroup(
            menuBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(menuBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newGameButton)
                    .addComponent(saveGameButton)
                    .addComponent(loadGameButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(labelA)
                        .addGap(40, 40, 40)
                        .addComponent(labelB)
                        .addGap(42, 42, 42)
                        .addComponent(labelC)
                        .addGap(42, 42, 42)
                        .addComponent(labelD)
                        .addGap(42, 42, 42)
                        .addComponent(labelE)
                        .addGap(43, 43, 43)
                        .addComponent(labelF)
                        .addGap(43, 43, 43)
                        .addComponent(labelG)
                        .addGap(41, 41, 41)
                        .addComponent(labelH))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label8)
                            .addComponent(label7)
                            .addComponent(label6)
                            .addComponent(label5)
                            .addComponent(label4)
                            .addComponent(label3)
                            .addComponent(label2)
                            .addComponent(label1))
                        .addGap(18, 18, 18)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outOfPlayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(durationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(menuBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(label8)
                        .addGap(35, 35, 35)
                        .addComponent(label7)
                        .addGap(33, 33, 33)
                        .addComponent(label6)
                        .addGap(33, 33, 33)
                        .addComponent(label5)
                        .addGap(35, 35, 35)
                        .addComponent(label4)
                        .addGap(33, 33, 33)
                        .addComponent(label3)
                        .addGap(35, 35, 35)
                        .addComponent(label2)
                        .addGap(34, 34, 34)
                        .addComponent(label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(durationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(outOfPlayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA)
                    .addComponent(labelB)
                    .addComponent(labelC)
                    .addComponent(labelD)
                    .addComponent(labelE)
                    .addComponent(labelF)
                    .addComponent(labelG)
                    .addComponent(labelH))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveGameButtonActionPerformed

    private void loadGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChessGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton E8;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JButton G1;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton G5;
    private javax.swing.JButton G6;
    private javax.swing.JButton G7;
    private javax.swing.JButton G8;
    private javax.swing.JButton H1;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton H6;
    private javax.swing.JButton H7;
    private javax.swing.JButton H8;
    private javax.swing.JLabel blackLabel;
    private javax.swing.JPanel durationPanel;
    private javax.swing.JLabel durationText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelB;
    private javax.swing.JLabel labelC;
    private javax.swing.JLabel labelD;
    private javax.swing.JLabel labelE;
    private javax.swing.JLabel labelF;
    private javax.swing.JLabel labelG;
    private javax.swing.JLabel labelH;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuBarPanel;
    private javax.swing.JButton newGameButton;
    private javax.swing.JPanel outOfPlayPanel;
    private javax.swing.JButton saveGameButton;
    private javax.swing.JLabel whiteLabel;
    // End of variables declaration//GEN-END:variables
}
